---
title: Building your Function Vocabulary
date: 06-Oct-2015
output: 
    html_document:
        css: styles.css
---
<style type="text/css">
    td:first-child {
        width: 25%;
    }
</style>

__Preface__: This markdown file assumes that you have done at least one of the introductory online courses mentioned in the main page, and have gotten a basic feel of working with the R console. If you haven't, head to [CodeSchool](http://tryr.codeschool.com) now to get started.

In order to speak a language, you need building blocks for constructing your sentences: vocabulary. This page provides a *very condensed* list of basic functions that I have found most useful in my own experience. For a slightly more extensive and advanced reference, see Hadley Wickham's own vocab list [here](http://adv-r.had.co.nz/Vocabulary.html).

--------

### 1. Exploring objects in the workspace ###

After working with R for some time, you may end up having many objects in your workspace.  The following list of commands will help you retrieve information about the characteristics about these objects.

Code                      | Notes
--------------------------|--------------------------
`length(obj)`             | Tells you how many elements are in an object
`attributes(obj)`         | Many objects from complicated classes (e.g. *ggplot*, *lm*) are *lists* of named, varied elements. 
`names(obj) `             | Some objects have names assigned to their elements. For *list*-type objects, you can access named elements using `$`
`class(obj)`              | An object's 'type' is called its *class* (e.g. *data frame*, *numeric*, or *list*)
`dim(obj)`                | Displays the dimension of the object.
`str(obj)`                | Shows the structure of the object
`summary(obj)`            | Most useful for variables in a *data frame* and *lm* objects


Attributes store important information about objects. The three most important types of attributes are names, class and dimension. The `str` and `summary` functions are useful for seeing a quick snapshot of your object.

--------

<br>

### 2. Basic Data Manipulation ###

#### Creating Data ####

The easiest way to have data is to create it yourself. R stores data in various types. There are two types of object classes: those that take different elements (heterogeneous) and those that take elements of the same class (homogeneous).

Code                      | Notes
--------------------------|----------------------------------
`list()`                  | Creates a list of things (can be different of different classes)
`c(); matrix(); array()`  | Creates a 1-dimensional, 2-dimensional or n-dimensional vector (all elements must be of the same class)
`seq(1, 11)`              | Generates a *sequence* of integers from 1 to 11. Arguments: `by =`; `length.out =`
`seq_len(n); 1:n`         | Generates a *sequence* of integers from 1 to n
`seq_along(obj)`          | Generates a *sequence* of integers from 1 to `m`, where `m = length(obj)`
`rep("Hello", 4)`         | Generates a *vector* of 4 `"Hello"`s
`rep_len(1:3, 10)`        | Generates a *sequence* by repeating 1, 2, 3 until the sequence hits length 10
`rev()`                   | Reverses a *sequence*

For homogeneous data structures such as vectors, elements will be **coerced** to the same class (see coercion functions below). For example, if you try to "force" a character and a numeric value into a vector, everything will be *coerced* to the character class. The hierarchy of flexibility, from most to least, is **character**, **double**, **integer**, **logical**.

<br>

#### Assignment & Subsetting ####

After we have created data, we need to 1) save it as objects in the workspace (assignment) and 2) retrieve all or part (subsetting) of these objects.

Code                      | Notes
--------------------------|----------------------------------
`=  <-  <<-`              | Assignment operators
`[  [[  $`                | Subsetting operators

#### Numeric Data ####

Usually, datasets pulled from registry or other sources will be formatted in a less-than-perfect way. You may need functions to transform data values. The following functions work with both individual values as well as on multiple values stored in a *vector*.

Code                      | Notes
--------------------------|----------------------------------
`+  -  *  /  ^`           | Basic arithmetic operations
`%%  %/%`                 | Modulus; integer division
`log(); log10(); exp()`   | Natural log; log base 10; exponential
`sin(); cos(); tan()`     | Trigonometric functions
`abs(); sqrt(); sign()`   | Absolute; square root; positivity
`round(x, 3)`             | Rounds `x` to 3 decimal places
`signif(x, 3)`            | Rounds `x` to 3 significant figures
`ceiling(); floor()`      | Round up or down to the nearest integer

#### Strings ####

*Strings* in R are identifiable by their class, which is *character*. Note that the following functions may produce results contrary to what you expect if you tried to use them on *numeric* or other data types.

Code                      | Notes
--------------------------|----------------------------------
`paste(x, y)`             | Concatenates `x` and `y` into one string. Arguments: `collapse =` or `sep =`.
`grep(); grepl()`         | Functions that search a *string* for a pattern
`sub(); gsub()`           | Functions that substitute a pattern within a *string*
`tolower(); toupper()`    | Functions that force a *string* to all lowercase or uppercase letters
`substr(x, 2, 5)`         | Extracts the 2nd to 5th characters in the *string* `x`
`nchar()`                 | Counts the number of characters in the *string*
`strsplit(x, " ")`        | Splits `x` into multiple *strings*, cutting it every time there is a space

<br><br>

### 3. Programming ###

This section shows simple control structures and syntax for creating expressions and equations with the objects in your workspace. They provide important links between functions - you can think of them as the grammar of the scripting language.

<br>

#### Coercion and Test Functions ####

There are 2 important families of functions that are applied to individual elements or objects. The first concerns functions for coercion, which is forcing a change of an object from one *class* to another. The second family tests whether objects correspond to a certain type and are useful for fortifying your code, making it more resilient to irregular data types.  

__Coercion__: `as.numeric(); as.character(); as.data.frame(); as.matrix(); as.list(); as.factor()`  
__Tests__: `is.numeric(); is.character(); is.data.frame(); is.ggplot(); is.na(); is.nan()` 

<br>

#### Comparison ####

Code                      | Notes
--------------------------|----------------------------------
`==  !=  <  >  <=  >=`    | Logical tests which return *logical*  values
`5 %in% c(1, 3, 5)`       | Returns `TRUE` since the value 5 is found in the *vector* on the right
`all.equal(x, y)`         | Checks if (each component in) `x` is equal to `y`

#### Logic ####

Code                      | Notes
--------------------------|----------------------------------
`&  |  !`                 | Logical operators for "*and*", "*or*", "*not*"
`any(a, b, c)`            | Returns `TRUE` if either `a`, `b` or `c` is satisfied
`all(a, b, c)`            | Returns `TRUE` if `a`, `b` and `c` are all satisfied
`which(x>5)`              | Which elements in the *vector* `x` are larger than 5?

#### Control Structures ####

Code                      | Notes
--------------------------|----------------------------------
`ifelse(expr, A, B)`      | If the `expr` condition is `TRUE`, return the value `A`, if not return the value `B`
`for(i in 1:10){do this}` | Creates a __for__ loop iterating from `i=1` to `i=10`
`while(i < 10){do this}`  | Creates a __while__ loop. NOTE: You should use this with caution & insert `break`s appropriately
`next; break`             | `next` moves to the following iteration of the loop while `break` exits the loop altogether
`if(expr){ABC} else{DEF}` | If `expr` is true, execute commands `ABC`, otherwise execute commands `DEF`
`apply(df, 2, function)`  | Takes the *data frame* `df`, applies `function` to each of its columns (`2`)
`lapply(); sapply()`      | Similar to __apply__ but takes lists as their inputs. __sapply__ simplifies the result while __lapply__ leaves it as a list

<br><br>


### 4. Handling Data (Columns of Values) ###

Certain functions are only meaningful when applied to an array of values. These are especially useful for working with variables in a table. These functions mostly derive from in-built packages in R. I will introduce the more powerful data manipulation package `dplyr` in an upcoming session.

Code                      | Notes
--------------------------|----------------------------------
`cut()`                   | Creates a categorical variable from a continuous variable. Arguments: `breaks =` and `labels = `
`unique()`                | Displays the unique values of a variable. Similar (but not equivalent) to `names(table())`
`subset(df, expr)`        | Subsets out rows of `df` which meet the `expr` condition. Note that typing `df$` is generally not needed
`levels()`                | Displays the values taken by a *factor* variable
`scale()`                 | Normalizes data into Z-scores
`mean(), median()`        | Mean & Median. Use the argument `na.rm = T` to remove NA values
`quantile()`              | Produces quantiles other than the median, specified in the argument `probs =`
`rank()`                  | Returns the ranks of the values in a variable. Break ties with the argument `ties.method =`
`sort()`                  | Sorts the data in ascending or descending (Argument:`decreasing = F`) order

<br><br>

### 5. Manipulating Data Frames  ###

Finally, we have a series of functions for working with arrays like *tables*, *data frames* and *matrices*. Again, some of these will be superseded by functions in `dplyr` but I present them here for completeness.

Code                      | Notes
--------------------------|----------------------------------
`t()`                     | Transposes a *data frame* or *matrix* (also coerces the object *class* into a *matrix*)
`nrow(); ncol()`          | Like __dim__ but only for 2-dimensional objects like tables
`row.names(); colnames()` | Gives the row & column names of a *data frame*
`rbind(); cbind()`        | Used for row- or column-binding two arrays
`merge(); plyr::join()`   | For joining arrays; `plyr::` indicates that you must first load the package `plyr`
`head(); tail()`          | Displays the first or last few rows of a *data frame*. Use the argument `n = ` for the number of rows
`rowSums(); colSums()`    | Computes the sum of each row or column of a *data frame*
`rowMeans(); colMeans()`  | Computes the mean of each row or column of a *data frame*

<br>
